vhosts:
  - servername: www.domain1.tld
    documentroot: /www/domain1
    serveradmin: admin1@example.com
    directorypath: /usr/local/httpd/htdocs
    active: true

  - servername: www.domain2.tld
    documentroot: /www/domain2
    serveradmin: admin2@example.com
    directorypath: /usr/local/httpd/htdocs
    active: false

  - servername: www.domain3.tld
    documentroot: /www/domain3
    serveradmin: admin3@example.com
    directorypath: /usr/local/httpd/htdocs
    active: true
